version: "3.9"

services:
  flaskr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: flaskr:create_app
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:example@db:5432/flaskr
      PYTHONPATH: /app
    depends_on:
      - db
    # volumes:
    #   - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: flaskr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
