version: "3.9"

services:
  flaskr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - flaskr-instance:/app/instance
    command:
      flask --app flaskr run --host=0.0.0.0 --port=5000

volumes:
  flaskr-instance:
